import Head from "next/head";

import Hero from "../components/hero";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Simplexology Lab</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Hero />
      </main>

      <footer>
        <p>Est 2020</p>
      </footer>
    </div>
  );
}
