import Head from "next/head";

import Hero from "../components/hero";
import Mission from "../components/mission";
import Services from "../components/services";
import Contact from "../components/contact";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Simplexology Lab</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="font-mono">
        <Hero />
        <Mission />
        <Services />
        <Contact />
      </main>

      <footer>
        <p>Est 2020</p>
      </footer>
    </div>
  );
}
